# Generated by Django 3.0.5 on 2020-05-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SID', models.CharField(max_length=20)),
                ('date_time', models.DateTimeField()),
                ('in_out', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SID', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('school', models.CharField(max_length=20)),
                ('year', models.DecimalField(decimal_places=0, max_digits=1)),
                ('address', models.CharField(max_length=50)),
                ('student_phone', models.CharField(max_length=20)),
                ('parent', models.CharField(max_length=10)),
                ('parent_phone', models.CharField(max_length=20)),
                ('sibling_name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
