# Generated by Django 3.0.5 on 2020-05-09 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FengCramSchool', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel('Attendence', 'Attendance')
    ]

