# Generated by Django 3.0.6 on 2020-05-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FengCramSchool', '0003_auto_20200509_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('class_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CramRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SID', models.CharField(max_length=20)),
                ('quizID', models.CharField(max_length=20)),
                ('quiz_grade', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizID', models.CharField(max_length=20)),
                ('quiz_date', models.DateField()),
                ('quiz_description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SID', models.CharField(max_length=20)),
                ('scholarshipID', models.CharField(max_length=20)),
                ('payment_date', models.DateField()),
                ('scholarship_description', models.CharField(max_length=20)),
                ('scholarship_payment', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SID', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('record_url', models.URLField()),
                ('grade', models.CharField(max_length=20)),
                ('scholarshipID', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tuition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SID', models.CharField(max_length=20)),
                ('received_date', models.DateField()),
                ('courseID', models.CharField(max_length=20)),
                ('tuition_payment', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VID', models.CharField(max_length=20)),
                ('courseID', models.CharField(max_length=20)),
                ('video_url', models.URLField()),
                ('course_date', models.DateField()),
            ],
        ),
    ]
