# Generated by Django 3.0.5 on 2020-05-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FengCramSchool', '0004_courseschedule_cramrecord_quiz_scholarship_schoolrecord_tuition_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='in_out',
            field=models.BooleanField(blank=True),
        ),
    ]
