# Generated by Django 3.0.5 on 2020-05-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FengCramSchool', '0005_auto_20200517_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='in_out',
            field=models.NullBooleanField(),
        ),
    ]
