# Generated by Django 3.0.5 on 2020-05-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FengCramSchool', '0008_auto_20200517_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='in_out',
            field=models.CharField(blank=True, choices=[('in', 'IN'), ('out', 'OUT')], default='in', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='schoolrecord',
            name='subject',
            field=models.CharField(blank=True, choices=[('math', 'Math'), ('english', 'English'), ('chinese', 'Chinese')], default='math', max_length=20, null=True),
        ),
    ]
