# Generated by Django 3.0.5 on 2020-05-17 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FengCramSchool', '0011_auto_20200517_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='scholarshipID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='school_record', to='FengCramSchool.SchoolRecord'),
        ),
    ]
