# Generated by Django 3.0.5 on 2020-05-17 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FengCramSchool', '0012_auto_20200517_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='school_record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='school_record', to='FengCramSchool.SchoolRecord'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='scholarshipID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
