# Generated by Django 3.0.5 on 2020-05-17 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FengCramSchool', '0013_auto_20200517_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuition',
            name='course_schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_schedule', to='FengCramSchool.CourseSchedule'),
        ),
    ]
