# Generated by Django 3.0.5 on 2020-05-17 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FengCramSchool', '0015_auto_20200517_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='SID',
        ),
        migrations.RemoveField(
            model_name='cramrecord',
            name='SID',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='SID',
        ),
        migrations.RemoveField(
            model_name='schoolrecord',
            name='SID',
        ),
        migrations.RemoveField(
            model_name='tuition',
            name='SID',
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_student_info', to='FengCramSchool.StudentInfo'),
        ),
        migrations.AddField(
            model_name='cramrecord',
            name='student_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cramRecord_student_info', to='FengCramSchool.StudentInfo'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='student_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_student_info', to='FengCramSchool.StudentInfo'),
        ),
        migrations.AddField(
            model_name='schoolrecord',
            name='student_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schoolRecord_student_info', to='FengCramSchool.StudentInfo'),
        ),
        migrations.AddField(
            model_name='tuition',
            name='student_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tuition_student_info', to='FengCramSchool.StudentInfo'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='school_record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_school_record', to='FengCramSchool.SchoolRecord'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='course_schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tuition_course_schedule', to='FengCramSchool.CourseSchedule'),
        ),
    ]
