# Generated by Django 3.0.5 on 2020-05-17 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FengCramSchool', '0016_auto_20200517_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cramrecord',
            name='quizID',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='scholarshipID',
        ),
        migrations.RemoveField(
            model_name='tuition',
            name='courseID',
        ),
        migrations.AddField(
            model_name='cramrecord',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cramRecord_quiz', to='FengCramSchool.Quiz'),
        ),
    ]
